version: 2

models:

  - name: shopify_orders
    columns:
    - name: cart_token
      tests:
      - unique

    - name: customer_id
      tests:
      - relationships:
          field: id
          to: ref('shopify_customers')

    - name: id
      tests:
      - not_null
      - unique

  - name: shopify_checkouts
    columns:
    - name: cart_token
      tests:
      - unique

    - name: customer_id
      tests:
      - relationships:
          field: id
          to: ref('shopify_customers')
    - name: id
      tests:
      - not_null
      - unique

  - name: shopify_customers
    columns:
    - name: id
      tests:
      - not_null
      - unique

  - name: shopify_discount_codes
    columns:
    - name: order_id
      tests:
      - not_null
      - relationships:
          field: id
          to: ref('shopify_orders')

  - name: shopify_transactions
    columns:
    - name: id
      tests:
      - not_null
      - unique

    - name: order_id
      tests:
      - not_null
      - relationships:
          field: id
          to: ref('shopify_orders')

  - name: shopify_refunds
    columns:
    - name: id
      tests:
      - not_null
      - unique
    - name: order_id
      tests:
      - not_null
      - relationships:
          field: id
          to: ref('shopify_orders')

  - name: shopify_products
    columns:
    - name: id
      tests:
      - not_null
      - unique

  - name: shopify_order_items
    columns:
    - name: id
      tests:
      - not_null
      - unique
    - name: order_id
      tests:
      - not_null
      - relationships:
          field: id
          to: ref('shopify_orders')

    - name: product_id
      tests:
      - relationships:
          field: id
          to: ref('shopify_products')
